# Generated by Django 5.1.5 on 2025-01-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_en',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_ru',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescribed_medication_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescribed_medication_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='specialty_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='specialty_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
