# Generated by Django 5.1.5 on 2025-01-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_medicalrecord_diagnosis_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
