# Generated by Django 5.1.5 on 2025-01-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ward',
            old_name='totel_people',
            new_name='total_people',
        ),
    ]
