# Generated by Django 5.1.5 on 2025-02-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_rename_totel_people_ward_total_people'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
    ]
