# Generated by Django 5.1.5 on 2025-02-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_alter_doctor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='diagnosis_en',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='diagnosis_ru',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='treatment_en',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='treatment_ru',
        ),
    ]
