# Generated by Django 5.1.5 on 2025-02-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0006_remove_medicalrecord_diagnosis_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_ru',
            field=models.TextField(null=True),
        ),
    ]
