# Generated by Django 5.1.5 on 2025-02-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_medicalrecord_treatment_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
